name: train
channels:
  - defaults
  - pytorch-lts
  - nvidia
  - conda-forge
dependencies:
  - python=3.7
  - nltk
  - sentencepiece
  - pandas
  - cython
  - torchvision
  - fastbpe
  - faiss-gpu
  - scikit-learn
  - jupyter
  - matplotlib
  - seaborn
  - mpl-probscale
  - setuptools==59.5.0
  - pytorch==1.8.2
  - torchvision
  - torchaudio
  - cudatoolkit=11.1
  - tensorboard
  - sacremoses
